spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

#mybatis的整合
mybatis:
  #mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  #所有bean别名类所在包
  type-aliases-package: com.hugang.springcloud.beans
  #mapper映射文件
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
    #服务名称
    name: microservicecloud-config-dept-client
  #数据源配置
  datasource:
    #当前数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql的驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    #数据库路径和名称
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    #访问的连接池配置
    dbcp2:
      #数据库连接池的最小维持连接数
      min-idle: 5
      #初始化连接数
      initial-size: 5
      #最大连接数：
      max-idle: 20
      #等待连接获取的最大超时时间(毫秒)
      max-wait-millis: 200

eureka:
  client:
    #将客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: hugang-microservicecloud
  company.name: www.hugang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001

#mybatis的整合
mybatis:
  #mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  #所有bean别名类所在包
  type-aliases-package: com.hugang.springcloud.beans
  #mapper映射文件
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: test
  application:
    #服务名称
    name: microservicecloud-config-dept-client
  #数据源配置
  datasource:
    #当前数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql的驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    #数据库路径和名称
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    #访问的连接池配置
    dbcp2:
      #数据库连接池的最小维持连接数
      min-idle: 5
      #初始化连接数
      initial-size: 5
      #最大连接数：
      max-idle: 20
      #等待连接获取的最大超时时间(毫秒)
      max-wait-millis: 200

eureka:
  client:
    #将客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: hugang-microservicecloud
  company.name: www.hugang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$